apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express
  namespace: tools
spec:
  rules:
    - host: dev-mongo-ui.example.com
  tls:
    - hosts:
        - dev-mongo-ui.example.com
